"""empty message

Revision ID: 905ab9877bc2
Revises: 
Create Date: 2022-03-15 23:21:00.087556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905ab9877bc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('slack_token', sa.Text(), nullable=True),
    sa.Column('slack_bot', sa.Text(), nullable=True),
    sa.Column('slack_flag', sa.Integer(), server_default='0', nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=45), server_default='TEST', nullable=False),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('tool', sa.String(length=45), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('tracking', sa.Integer(), server_default='0', nullable=False),
    sa.Column('startday', sa.DateTime(), nullable=False),
    sa.Column('testlinkday', sa.DateTime(), nullable=True),
    sa.Column('start_test', sa.Integer(), nullable=True),
    sa.Column('livelinkday', sa.DateTime(), nullable=True),
    sa.Column('test_live', sa.Integer(), nullable=True),
    sa.Column('endday', sa.DateTime(), nullable=True),
    sa.Column('live_end', sa.Integer(), nullable=True),
    sa.Column('start_end', sa.Integer(), nullable=True),
    sa.Column('testqc', sa.Integer(), nullable=True),
    sa.Column('liveqc', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('sample', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
